name: Release

# Controls when the action will run. Triggers the workflow on push tags
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Get Commit Message to be used in release
      - name: Get commit Message
        run: echo ::set-env name=commitmsg::$(git log --pretty="%h - %s (%an)" $(git describe --tags --abbrev=0)..@)
        # Creating a new Release
      - id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.commitmsg }}
          draft: false
          prerelease: false