on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set release tag
        run: |
          export CURRENT_TAG="$(git describe --tags --abbrev=0)"
          export LAST_TAG="$(echo $(git tag -l | sort -V --reverse | sed -n 2p) | sed 's/^$/HEAD/')"
          export CHANGELOG_FROM="$(if [ "$LAST_TAG" = "HEAD" ]; then echo "$LAST_TAG..HEAD"; else echo "$CURRENT_TAG...$LAST_TAG"; fi;)"
      - name: 'Prepare the changelog'
        id: prepare_changelog
        run: |
          changelog="$(git log --pretty="%h - %s (%an)" $CHANGELOG_FROM)"
          changelog=${changelog//$'\n'/'%0A'}
          echo "::set-output name=content::${changelog}"
      - id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.prepare_changelog.outputs.content }}
          draft: false
          prerelease: false