# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare release description
        id: prepare_changelog
        shell: bash
        run: |
          git fetch --tags
          export CURR_TAG="$(git describe --tags --abbrev=0)"
          printf 'CURR_TAG:\n%s\n' "${CURR_TAG}"
          export PREV_TAG="$(echo $(git tag -l | sort -V --reverse | sed -n 2p) | sed 's/^$/HEAD/')"
          printf 'PREV_TAG:\n%s\n' "${PREV_TAG}"
          export CHANGELOG_FROM="$(if [ "$PREV_TAG" = "HEAD" ]; then echo "$PREV_TAG..HEAD"; else echo "$CURR_TAG...$PREV_TAG"; fi;)"
          printf 'CHANGELOG_FROM:\n%s\n' "${CHANGELOG_FROM}"
          changelog="$(git log --pretty="%h - %s (%an)" $CHANGELOG_FROM)"
          printf 'changelog:\n%s\n' "${changelog}"
          # See https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          printf 'changelog:\n%s\n' "${changelog}"
          echo "::set-output name=changelog::${changelog}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "${{ steps.prepare_changelog.outputs.changelog }}"
          draft: false
          prerelease: false